name: Pull Request CI/CD
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:

jobs:
  primary:
    # see https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # - name: Install GraphicsMagick for tests
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install graphicsmagick
      - name: Print versions
        run: |
          cat /etc/os-release
          # gm version
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Store snapshots from tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: snapshots
          path: ${{ github.workspace }}/src/__snapshots__/
      - name: Run lint
        run: npm run lint
